### Site metadata

repository: MichaelCurrin/MichaelCurrin.github.io

### Build settings ###

url: https://michaelcurrin.github.io
baseurl: ""

permalink: pretty

google_analytics: UA-87705880-9

# Normally you don't need the plugins field if you have :jekyll_plugins but this was needed to avod
# a build error.
plugins:
  - jekyll-octicons

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - docs/
  - LICENSE
  - README.md
  - Makefile
  # Exclude in Jekyll 3 only
  - vendor/
  - Gemfile

### Theme settings ###

layout: stacked # stacked | sidebar

style: dark # light | dark

dark:
  icon_color: "#ffffff"
light:
  icon_color: "#24292e"

projects:
  sort_by: stars # pushed | stars
  limit: 12
  exclude:
    archived: true
    forks: false
    projects:
    # - repo-name

social_media:
  # instagram: your_username
  # linkedin: your_username
  # medium: your_username
  # stackoverflow: 6250733 # Set but decided not to use
  # twitter: your_username
  # website: http://your_website_url
  # youtube: your_username

# source means original, i.e. not forked.
topics:
  - name: Python
    web_url: https://github.com/MichaelCurrin?tab=repositories&q=&type=source&language=python&sort=
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/python/python.png

  - name: JavaScript
    web_url: https://github.com/MichaelCurrin?tab=repositories&q=&type=source&language=javascript&sort=
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/javascript/javascript.png

  - name: TypeScript
    web_url: https://github.com/MichaelCurrin?tab=repositories&q=&type=source&language=typescript&sort=
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/typescript/typescript.png

  - name: Bash / Shell
    web_url: https://github.com/MichaelCurrin?tab=repositories&q=&type=source&language=shell&sort=
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/bash/bash.png

  - name: Jekyll
    web_url: https://michael-currin.netlify.app/topics/#topic-jekyll
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/jekyll/jekyll.png

  - name: Go
    web_url: https://github.com/MichaelCurrin?tab=repositories&q=&type=source&language=go&sort=
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/go/go.png
